ds_settings:

  classes: ["biological", "glass", "metal", "paper", "plastic"]
  num_classes: 5
  img_shape: [96, 96, 3]
  rescale: [0, 1]
  batch_size: 64
  val_split: 0.1

augmentation_settings:

  use_augmentation: false
  flip_type: "horizontal_and_vertical"
  rotation: 0.05
  zoom: [-0.05, 0.05]
  contrast: 0.05
  brightness: 0.05
  fill_mode: "constant"
